# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=200)),
                ('roll_no', models.IntegerField(null=True)),
            ],
        ),
    ]
